name: cssp
channels:
  - sssdgc
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - atk-1.0
  - binutils_impl_linux-64
  - binutils_linux-64
  - blas
  - boost-cpp
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cfitsio
  - curl
  - expat
  - fftw
  - firefox
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - freexl
  - fribidi
  - gcc_impl_linux-64
  - gcc_linux-64
  - gdal
  - gdk-pixbuf
  - geos
  - geotiff
  - gettext
  - ghostscript
  - giflib
  - gmp
  - gnutls
  - graphite2
  - graphviz
  - gtk2
  - gts
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - imagemagick
  - jbig
  - joblib
  - jpeg
  - json-c
  - kealib
  - krb5
  - lame
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcurl
  - libcxx
  - libcxxabi
  - libdap4
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgd
  - libgdal
  - libgfortran
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libiconv
  - libidn2
  - libkml
  - liblapack
  - libllvm10
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libopus
  - libpng
  - libpq
  - librsvg
  - librttopo
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libtool
  - libunistring
  - libuuid
  - libuv
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - llvm-openmp
  - llvmlite
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - nodejs
  - numba
  - numpy
  - numpy-base
  - openh264
  - openjpeg
  - openssl
  - pandas
  - pango
  - patsy
  - pcre
  - perl
  - pip
  - pixman
  - pkg-config
  - poppler
  - poppler-data
  - postgresql
  - proj
  - proj-data
  - pthread-stubs
  - python
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - scipy
  - setuptools
  - six
  - sqlcipher
  - sqlite
  - statsmodels
  - tabulate
  - tbb
  - threadpoolctl
  - tiledb
  - tk
  - tzcode
  - tzdata
  - wheel
  - x264
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd
  - pip:
    - affine
    - attrs
    - backcall
    - bidict
    - cached-property
    - chardet
    - click
    - click-plugins
    - cligj
    - cloudpickle
    - conda-pack
    - cycler
    - cython
    - dask
    - decorator
    - descartes
    - ffmpeg
    - fiona
    - flask
    - flask-socketio
    - flask-sqlalchemy
    - flask-statistics
    - fsspec
    - geopandas
    - greenlet
    - h5py
    - idna
    - importlib-metadata
    - iniconfig
    - ipykernel
    - ipython
    - ipython-genutils
    - itsdangerous
    - jedi
    - jinja2
    - json5
    - jsonschema
    - jupyter-client
    - jupyter-core
    - kiwisolver
    - locket
    - markdown
    - markupsafe
    - matplotlib
    - munch
    - oauthlib
    - packaging
    - parso
    - partd
    - pexpect
    - pickleshare
    - pillow
    - pluggy
    - prompt-toolkit
    - ptyprocess
    - py
    - pyasn1
    - pygments
    - pyparsing
    - pyproj
    - pyrsistent
    - pytest
    - python-engineio
    - python-socketio
    - pyyaml
    - pyzmq
    - rasterio
    - requests
    - requests-oauthlib
    - rsa
    - seaborn
    - shapely
    - simplejson
    - snuggs
    - sqlalchemy
    - toml
    - toolz
    - topojson
    - tornado
    - traitlets
    - typing-extensions
    - urllib3
    - wcwidth
    - werkzeug
    - zipp
