name: cssp
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - ca-certificates
  - certifi
  - icu
  - joblib
  - libblas
  - libcblas
  - libcxx
  - libedit
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libllvm10
  - libopenblas
  - libuv
  - llvm-openmp
  - ncurses
  - nodejs
  - numba
  - numpy
  - openssl
  - patsy
  - pip
  - python
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - scipy
  - setuptools
  - six
  - sqlite
  - statsmodels
  - threadpoolctl
  - tk
  - wheel
  - xz
  - zlib
  - python=3.7
  - pip:
    - cycler
    - cython
    - dask
    - descartes
    - flask
    - geopandas
    - h5py
    - ipykernel
    - ipython
    - ipython-genutils
    - itsdangerous
    - jedi
    - jinja2
    - json5
    - jsonschema
    - llvmlite
    - markdown
    - markupsafe
    - matplotlib
    - oauthlib
    - pillow
    - pysqlcipher3
    - pytest
    - pyyaml
    - pyzmq
    - rasterio
    - requests
    - requests-oauthlib
    - rsa
    - seaborn
    - shapely
    - simplejson
    - topojson
    - urllib3
    - werkzeug
    - pysqlcipher3 
