name: cssp
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - ca-certificates
  - certifi
  - icu
  - joblib
  - libblas
  - libcblas
  - libcxx
  - libedit
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libllvm10
  - libopenblas
  - libuv
  - llvm-openmp
  - ncurses
  - nodejs
  - numba
  - numpy
  - openssl
  - patsy
  - pip
  - python
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - scipy
  - setuptools
  - six
  - sqlite
  - statsmodels
  - threadpoolctl
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - absl-py
    - affine
    - anyio
    - appnope
    - argon2-cffi
    - async-generator
    - attrs
    - babel
    - backcall
    - bleach
    - cachetools
    - cffi
    - chardet
    - click
    - click-plugins
    - cligj
    - cloudpickle
    - cycler
    - cython
    - dask
    - decorator
    - defusedxml
    - descartes
    - distributed
    - entrypoints
    - fiona
    - flask
    - flatbuffers
    - fsspec
    - gast
    - geopandas
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h5py
    - heapdict
    - idna
    - iniconfig
    - ipykernel
    - ipython
    - ipython-genutils
    - itsdangerous
    - jedi
    - jinja2
    - json5
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyter-server
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - keras-preprocessing
    - kiwisolver
    - llvmlite
    - locket
    - markdown
    - markupsafe
    - matplotlib
    - mistune
    - msgpack
    - munch
    - nbclassic
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - oauthlib
    - opt-einsum
    - packaging
    - pandas
    - pandocfilters
    - parso
    - partd
    - pexpect
    - pickleshare
    - pillow
    - pluggy
    - pmdarima
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - py
    - pyasn1
    - pyasn1-modules
    - pycparser
    - pygments
    - pyparsing
    - pyproj
    - pyrsistent
    - pysqlcipher3
    - pytest
    - pyyaml
    - pyzmq
    - rasterio
    - requests
    - requests-oauthlib
    - rsa
    - scikit-learn
    - scikit-posthocs
    - seaborn
    - send2trash
    - shapely
    - simplejson
    - sktime
    - sniffio
    - snuggs
    - sortedcontainers
    - tblib
    - tensorboard
    - tensorboard-plugin-wit
    - tensorflow-estimator
    - termcolor
    - terminado
    - testpath
    - toml
    - toolz
    - topojson
    - tornado
    - tqdm
    - traitlets
    - tsfresh
    - typing-extensions
    - urllib3
    - wcwidth
    - webencodings
    - werkzeug
    - wrapt
    - zict
