name: cssp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - mamba
  - nodejs
  - ca-certificates
  - certifi
  - openssl
  - rioxarray
  - ffmpeg
  - imagemagick
  - geopandas
  - h5py
  - pip
  - cftime
  - geopandas
  - pip:
    - flask
    - flask-socketio
    - flask-sqlalchemy
    - flask-statistics
    - rasterio
    - shapely
    - sqlalchemy
    
